project_name: TuT
authors: [eileenforwhat, simonseo, yuhsuanyeh]
story_builder:
  num_sentences: 10  # length of story in number of sentences
  openai_api_key: "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"
illustrator:
  model_id: "stabilityai/stable-diffusion-2"  # ID of huggingface diffuser model
  inference_steps: 50  # number of iterations of stable diffusion per image
  prefix: "mdjrny-v4 Pixar movie capture of "
  suffix: " low detail, unreal engine, symmetrical face, laurie greasley, akira toriyama, james gilleard, acrylic palette knife, 4k, vibrant colors, dusty haze, volumetric lighting, medieval"
  negative_prompt: "bad anatomy, extra legs, extra arms, poorly drawn face, poorly drawn hands, poorly drawn feet, fat, disfigured, out of frame, long neck, bad hands, bad art, deformed, gun, double head, portrait"
  custom_type: "textual-inversion"
  custom_args:
    learning_rate: 0.0001
    train_batch_size: 16
    max_train_steps: 100
    mixed_precision: "no"
    gradient_checkpointing: True
    enable_xformers_memory_efficient_attention: True
    logging_dir: "runs/text-inversion-model"
    train_text_encoder: False
    use_8bit_adam: False
