project_name: TuT
authors: [eileenforwhat, simonseo, yuhsuanyeh]
story_builder:
  num_sentences: 10  # length of story in number of sentences
  openai_api_key: "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"
illustrator:
  model_id: "prompthero/openjourney"  # ID of huggingface diffuser model
  inference_steps: 50  # number of iterations of stable diffusion per image
  custom_type: "baseline"
  custom_args:
    prefix: "mdjrny-v4 Pixar movie capture of "
    suffix: ", group photo, 4k, 8k, unreal engine, octane render photorealistic by cosmicwonder, hdr, photography by cosmicwonder, high definition, symmetrical face, volumetric lighting, dusty haze, 24mm, DSLR, high quality, 60 fps"
    negative_prompt: "bad anatomy, extra legs, extra arms, poorly drawn face, poorly drawn hands, poorly drawn feet, fat, disfigured, out of frame, long neck, bad hands, bad art, deformed, gun, double head"
