project_name: TuT
authors: [eileenforwhat, simonseo, yuhsuanyeh]
story_builder:
  num_sentences: 5  # length of story in number of sentences
  openai_api_key: "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"
illustrator:
  model_id: "stabilityai/stable-diffusion-2"  # ID of huggingface diffuser model
  inference_steps: 50  # number of iterations of stable diffusion per image
  custom_type: "baseline"
  # custom_args:
  #   prefix: "mdjrny-v4 Pixar movie capture of "
  #   suffix: ", group photo, 4k, 8k, unreal engine, octane render photorealistic by cosmicwonder, hdr, photography by cosmicwonder, high definition, symmetrical face, volumetric lighting, dusty haze, 24mm, DSLR, high quality, 60 fps"
  #   negative_prompt: "bad anatomy, extra legs, extra arms, poorly drawn face, poorly drawn hands, poorly drawn feet, fat, disfigured, out of frame, long neck, bad hands, bad art, deformed, gun, double head"
  custom_args:
    output_dir: "text-inversion-model"
    mixed_precision: "no"
    pretrained_model_name_or_path: "duongna/stable-diffusion-v1-4-flax"
    gradient_checkpointing: True
    enable_xformers_memory_efficient_attention: True
    learning_rate: 1e-4
    train_batch_size: 16
    num_train_epochs: 100
    learnable_property: "object"
    prefix: "mdjrny-v4 Pixar movie capture of "
    suffix: " low detail, unreal engine, symmetrical face, laurie greasley, akira toriyama, james gilleard, acrylic palette knife, 4k, vibrant colors, dusty haze, volumetric lighting, medieval"
    negative_prompt: "bad anatomy, extra legs, extra arms, poorly drawn face, poorly drawn hands, poorly drawn feet, fat, disfigured, out of frame, long neck, bad hands, bad art, deformed, gun, double head, portrait"
