project_name: TuT
authors: [eileenforwhat, simonseo, yuhsuanyeh]
story_builder:
  num_sentences: 10  # length of story in number of sentences
  openai_api_key: "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"
illustrator:
  model_id: "stabilityai/stable-diffusion-2"  # ID of huggingface diffuser model
  inference_steps: 50  # number of iterations of stable diffusion per image
  custom_type: "dreambooth"
  custom_args:
    ...